source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project 'AimBrain Demo.xcodeproj'

pod 'Fabric'
pod 'Crashlytics'

target 'AimBrain Demo Banking Authentication' do
end

target 'AimBrain Demo_Tests' do
end
