source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'

target 'AimBrain Banking Demo', :exclusive => true do
end

target 'AimBrain_Tests', :exclusive => true do
end
